import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Providers } from "@/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className=" flex gap-5 w-full">
            <div className=" w-1/6 min-h-screen bg-gray-300">
              <NavBar />
            </div>
            <div className=" w-5/6  bg-gray-300 ">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
